<!-- Copyright © Erickson Lopez. MIT License. -->
<Project>

  <ItemGroup Condition="$(MSBuildProjectDirectory.Contains('tests'))">
    <Content Include="$(NuGetPackageRoot)xunit.runner.visualstudio\2.8.2\build\net6.0\xunit.runner.visualstudio.testadapter.dll"
             Link="xunit.runner.visualstudio.testadapter.dll"
             CopyToOutputDirectory="PreserveNewest"
             Visible="false" />
    <Content Include="$(NuGetPackageRoot)xunit.runner.visualstudio\2.8.2\build\net6.0\xunit.runner.reporters.netcoreapp10.dll"
             Link="xunit.runner.reporters.netcoreapp10.dll"
             CopyToOutputDirectory="PreserveNewest"
             Visible="false" />
    <Content Include="$(NuGetPackageRoot)xunit.runner.visualstudio\2.8.2\build\net6.0\xunit.runner.utility.netcoreapp10.dll"
             Link="xunit.runner.utility.netcoreapp10.dll"
             CopyToOutputDirectory="PreserveNewest"
             Visible="false" />
  </ItemGroup>

</Project>
